### ISSUE TITLE
Building and Running on MacOs

### ISSUE THREAD

**Issue by yrahulkr** [isa-group/RESTest#212]
Hey, I am trying to get started with RESTest. Here are a couple of issues I faced when building and running on your latest release. The build works fine after a bit of tweaking, but I get an error while running. I am using a MacBook with MacOS Catalina (10.15).

Any help is appreciated. 

`./scripts/install_dependencies.sh` did not work. I added a `#!/bin/sh` to make it work. 

When I ran `java -jar target/restest-full.jar src/test/resources/Restcountries/restcountries_demo.properties` I get this following error -

`2021-10-04 09:31:39 ERROR CSVManager:65 - Error parsing CSV file: target/test-data/restcountries/test-results_1hv5jbasfndpt.csv
2021-10-04 09:31:39 ERROR CSVManager:66 - Exception:
java.io.FileNotFoundException: target/test-data/restcountries/test-results_1hv5jbasfndpt.csv (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_201]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_201]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_201]
	at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[?:1.8.0_201]
	at java.io.FileReader.<init>(FileReader.java:58) ~[?:1.8.0_201]
	at es.us.isa.restest.util.CSVManager.readCSV(CSVManager.java:56) [restest-full.jar:1.2.1-SNAPSHOT]
	at es.us.isa.restest.util.CSVManager.readCSV(CSVManager.java:81) [restest-full.jar:1.2.1-SNAPSHOT]
	at es.us.isa.restest.util.TestManager.getTestResults(TestManager.java:35) [restest-full.jar:1.2.1-SNAPSHOT]
	at es.us.isa.restest.reporting.StatsReportManager.generateCoverageStats(StatsReportManager.java:226) [restest-full.jar:1.2.1-SNAPSHOT]
	at es.us.isa.restest.reporting.StatsReportManager.generateReport(StatsReportManager.java:93) [restest-full.jar:1.2.1-SNAPSHOT]
	at es.us.isa.restest.runners.RESTestRunner.generateReports(RESTestRunner.java:91) [restest-full.jar:1.2.1-SNAPSHOT]
	at es.us.isa.restest.runners.RESTestRunner.run(RESTestRunner.java:75) [restest-full.jar:1.2.1-SNAPSHOT]
	at es.us.isa.restest.main.TestGenerationAndExecution.main(TestGenerationAndExecution.java:148) [restest-full.jar:1.2.1-SNAPSHOT]
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.remove(ArrayList.java:496)
	at es.us.isa.restest.util.CSVManager.readCSV(CSVManager.java:83)
	at es.us.isa.restest.util.TestManager.getTestResults(TestManager.java:35)
	at es.us.isa.restest.reporting.StatsReportManager.generateCoverageStats(StatsReportManager.java:226)
	at es.us.isa.restest.reporting.StatsReportManager.generateReport(StatsReportManager.java:93)
	at es.us.isa.restest.runners.RESTestRunner.generateReports(RESTestRunner.java:91)
	at es.us.isa.restest.runners.RESTestRunner.run(RESTestRunner.java:75)
	at es.us.isa.restest.main.TestGenerationAndExecution.main(TestGenerationAndExecution.java:148)`

**Comment by AML14** [comment]
Hi @yrahulkr. Thanks for letting us know. Apparently, the Restcountries API that we use for demo purposes (https://restcountries.eu) has stopped working. We have replaced it with an alternative version (https://restcountries.com). Could you please check that everything works as expected now?

Thanks,
Alberto.

**Comment by yrahulkr** [comment]
I just did a `git pull` and that error has disappeared. Thanks!!
