### ISSUE TITLE
uncaught exception in getFuzzingValues if type is null.

### ISSUE THREAD

**Issue by c7h** [isa-group/RESTest#215]
Hello,

While generating fuzzing values for the  [OAS specification](https://github.com/free5gc/Nnrf_NFManagement/blob/master/api/openapi.yaml), an underhanded exception occurred. It seems to be caused by the _oneOf_ section here https://github.com/free5gc/Nnrf_NFManagement/blob/a680e6aa89ea3b8b7e266b892b05710fddf37581/api/openapi.yaml#L1741, which doesn't have a type. 

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "type" is null
        at es.us.isa.restest.inputs.fuzzing.FuzzingDictionary.getFuzzingValues(FuzzingDictionary.java:70)
        at es.us.isa.restest.generators.FuzzingTestCaseGenerator.createValueNode(FuzzingTestCaseGenerator.java:164)
        at es.us.isa.restest.generators.FuzzingTestCaseGenerator.generateFuzzingBody(FuzzingTestCaseGenerator.java:149)
        at es.us.isa.restest.generators.FuzzingTestCaseGenerator.generateFuzzingBody(FuzzingTestCaseGenerator.java:113)
        at es.us.isa.restest.generators.FuzzingTestCaseGenerator.generateNextTestCase(FuzzingTestCaseGenerator.java:95)
        at es.us.isa.restest.generators.FuzzingTestCaseGenerator.generateOperationTestCases(FuzzingTestCaseGenerator.java:73)
        at es.us.isa.restest.generators.AbstractTestCaseGenerator.generate(AbstractTestCaseGenerator.java:244)
        at es.us.isa.restest.generators.AbstractTestCaseGenerator.generate(AbstractTestCaseGenerator.java:165)
        at es.us.isa.restest.generators.AbstractTestCaseGenerator.generate(AbstractTestCaseGenerator.java:218)
        at es.us.isa.restest.runners.RESTestRunner.testGeneration(RESTestRunner.java:107)
        at es.us.isa.restest.runners.RESTestRunner.run(RESTestRunner.java:66)
        at es.us.isa.restest.main.TestGenerationAndExecution.main(TestGenerationAndExecution.java:148)
        
```

**Comment by c7h** [comment]
Linked Issue: https://github.com/isa-group/RESTest/issues/178
