### ISSUE TITLE
Error running restest.jar

### ISSUE THREAD

**Issue by henning410** [isa-group/RESTest#270]
Running the command `java -jar restest.jar -o /home/user/Desktop/vulnerable-nestjs-app/api.json` gives me the following error output: 

```
2024-05-10 10:22:29 ERROR PropertyManager:56 - Error reading property file: -o (No such file or directory)
2024-05-10 10:22:29 ERROR PropertyManager:57 - Exception: 
java.io.FileNotFoundException: -o (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[?:?]
        at java.io.FileInputStream.open(FileInputStream.java:216) ~[?:?]
        at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
        at java.io.FileInputStream.<init>(FileInputStream.java:111) ~[?:?]
        at es.us.isa.restest.util.PropertyManager.readProperty(PropertyManager.java:53) [restest.jar:1.4.0-SNAPSHOT]
        at es.us.isa.restest.main.TestGenerationAndExecution.readParameterValue(TestGenerationAndExecution.java:398) [restest.jar:1.4.0-SNAPSHOT]
        at es.us.isa.restest.main.TestGenerationAndExecution.readParameterValues(TestGenerationAndExecution.java:287) [restest.jar:1.4.0-SNAPSHOT]
        at es.us.isa.restest.main.TestGenerationAndExecution.main(TestGenerationAndExecution.java:88) [restest.jar:1.4.0-SNAPSHOT]
2024-05-10 10:22:29 ERROR PropertyManager:34 - Error reading property file: src/main/resources/config.properties (No such file or directory)
2024-05-10 10:22:29 ERROR PropertyManager:35 - Exception: 
java.io.FileNotFoundException: src/main/resources/config.properties (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[?:?]
        at java.io.FileInputStream.open(FileInputStream.java:216) ~[?:?]
        at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
        at java.io.FileInputStream.<init>(FileInputStream.java:111) ~[?:?]
        at es.us.isa.restest.util.PropertyManager.readProperty(PropertyManager.java:31) [restest.jar:1.4.0-SNAPSHOT]
        at es.us.isa.restest.main.TestGenerationAndExecution.readParameterValue(TestGenerationAndExecution.java:400) [restest.jar:1.4.0-SNAPSHOT]
        at es.us.isa.restest.main.TestGenerationAndExecution.readParameterValues(TestGenerationAndExecution.java:287) [restest.jar:1.4.0-SNAPSHOT]
        at es.us.isa.restest.main.TestGenerationAndExecution.main(TestGenerationAndExecution.java:88) [restest.jar:1.4.0-SNAPSHOT]
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:292 - Loading configuration parameter values
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:295 - Generator: null
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:298 - OAS path: null
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:301 - Test configuration path: null
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:304 - Target dir for test classes: null
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:307 - Experiment name: null
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:313 - Experiment execution: false
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:318 - Allure reports: false
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:325 - Proxy: null
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:329 - Check test cases: false
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:332 - Test class name: null
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:336 - Number of test cases per operation: null
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:340 - Max number of test cases: null
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:344 - Time delay: null
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:348 - Input data reloading  (CBT): null
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:352 - Max input test data (CBT): null
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:356 - Input coverage: null
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:360 - Output coverage: null
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:364 - CSV statistics: null
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:368 - Delete previous results: null
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:372 - Similarity metric: null
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:376 - Number of candidates: null
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:380 - Faulty ratio: null
2024-05-10 10:22:29 INFO  TestGenerationAndExecution:384 - Faulty dependency ratio: null
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "targetDir" is null
        at es.us.isa.restest.util.FileManager.createDir(FileManager.java:41)
        at es.us.isa.restest.main.TestGenerationAndExecution.main(TestGenerationAndExecution.java:101)
```

Do you know any solution for this?

**Comment by josgarmar31** [comment]
The error occurs because 'restest' has two JAR files: 'restest.jar' and 'restest-cli.jar'. To use the command line, it's necessary to employ the second mentioned file. You can execute the following command: 'java -jar .\target\restest-cli.jar -o [path_to_oas_file]'.
